spring:
  datasource:
    url: jdbc:mariadb://sti.iptime.org:3306/animalskin
    username: chkim
    password: Qwer1234!@#$
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mail:
    host: smtp.gmail.com
    username: chaehyun08032@gmail.com
    password: eoxocainowqttrno
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  coolsms:
    apikey: NCS6L9Q9DGJ9BQRC
    apisecret: HHRCPSGSYSKPQ57MTX1QPSZPLJ12ZB8A
    fromnumber: 01071595466
    provider: https://api.coolsms.co.kr

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 0bba7710cf392fabd1cceda7ae359050
            client-secret: CdRF8Ioxlzd7CNR9qIACjNzNhcYFq8kr
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao
          naver:
            client-id: 6e0pJHO14ubVyCFXI59f
            client-secret: jdtulf6BuG
            scope:
              - name
              - email
              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 30분
      persistent: true  # 세션을 지속적으로 유지

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

