spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
    
server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 30분
      persistent: true  # 세션을 지속적으로 유지

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
