spring:
  datasource:
    url: jdbc:mariadb://sti.iptime.org:3306/animalskin
    username: chkim
    password: Qwer1234!@#$
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dccbd05e3ad4d1afab58c50495021e5e
            client-secret: tOlEXTajl4Zy2ugOAmVqH0FK5ct5fMFl
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - name
              - profile_nickname
              - gender
              - birthday
              - birthyear
              - phone_number
              - shipping_address
            client-name: kakao
          naver:
            client-id: vbe2oSyR86x5AaA6R8dW
            client-secret: p7hzzYlGel
            scope:
              - name
              - email
              - gender
              - birthday
              - birthyear
              - mobile
              - nickname
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 30분
      persistent: true  # 세션을 지속적으로 유지

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

