spring:
  datasource:
    url: jdbc:mariadb://sti.iptime.org:3306/animalskin
    username: chkim
    password: Qwer1234!@#$
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mail:
    host: smtp.gmail.com
    username: chaehyun08032@gmail.com
    password: eoxocainowqttrno
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  coolsms:
    apikey: NCS6L9Q9DGJ9BQRC
    apisecret: HHRCPSGSYSKPQ57MTX1QPSZPLJ12ZB8A
    fromnumber: 01071595466
    provider: https://api.coolsms.co.kr

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: 0bba7710cf392fabd1cceda7ae359050
#            redirect_uri: http://localhost:8080/auth/login/kakao
jwt:
  secret-key: li4dGeRko4KZS2XE7Pt1KL1aookwWydTg3sqQzXEMduKz8kArz9Rlq2fuCBAtVSLJFOWNgGQQBRSh+hTZ6pXLA==

oauth:
  kakao:
    client-id: 0bba7710cf392fabd1cceda7ae359050
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  naver:
    secret: jdtulf6BuG
    client-id: 6e0pJHO14ubVyCFXI59f
    url:
      auth: https://nid.naver.com
      api: https://openapi.naver.com

server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 30분
      persistent: true  # 세션을 지속적으로 유지

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

