spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/test_db
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  mail:
    host: smtp.gmail.com
    username: chaehyun08032@gmail.com
    password: eoxocainowqttrno
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  coolsms:
    apikey: NCSPVFGMA894IBOX
    apisecret: TBPVJLLCPSVVOKE7HVNOAUOGY3BJRW98
    fromnumber: 01045710803
    provider: https://api.coolsms.co.kr

server:
  servlet:
    session:
      timeout: 30m  # 세션 유지 시간 30분
      persistent: true  # 세션을 지속적으로 유지

#  flyway:
#    enabled: true
#    baseline-on-migrate: true

